# nixaudio.rt — the scheduling privileges PipeWire's realtime module needs.
#
# WHAT IS ACTUALLY BROKEN, AND WHAT IS NOT
#
# It is easy to read `mod.rt: could not set nice-level to -11: Permission denied` in the PipeWire log
# and conclude realtime scheduling is broken. On the machine that produced this module it was not:
#
#   data-loop.0    SCHED_RR   priority 20
#   fabric-loop.0  SCHED_RR   priority 20
#
# The audio threads had genuine realtime scheduling. `@audio - rtprio 99` was present and the user
# was in the group. What was missing was RLIMIT_NICE, which governs only the negative *nice* value
# PipeWire additionally tries to set on its MAIN thread — a nicety, not the realtime path.
#
# So this module fixes a real gap without pretending it was the important one. The distinction
# matters because "audio crackles" and "the main thread runs at nice 0" are different problems, and
# conflating them sends the next person down the wrong path.
#
# ── WHY THE GROUP IS A NAME AND NEVER A NUMBER ──────────────────────────────────────────────────
#
# `nixiam.posix` is this fleet's single POSIX uid/gid registry: device groups are declared once and
# converge across every machine (`audio` is 403 here, alongside video 401, render 402, input 404).
# A limits.d line keyed on a NAME resolves through that registry. A module that invented its own gid
# would be declaring a second, competing number for one kernel namespace — exactly what the registry
# exists to prevent, and a failure that only shows up on the machine where the numbers disagree.
#
# So this module names the group and never numbers it. Where nixiam is composed, an assertion checks
# the group is actually declared there rather than assuming it exists.
{ lib, config, ... }:
let
  cfg = config.nixaudio.rt;

  posixGroups = (config.nixiam.posix.deviceGroups or { }) // (config.nixiam.posix.groups or { });
  nixiamComposed = config ? nixiam;

  limitsLines = lib.concatStringsSep "\n" (
    [
      "# Generated by nixaudio.rt -- do not edit."
      "#"
      "# rtprio governs the realtime scheduling the audio threads actually use."
      "# nice governs only the negative nice value PipeWire additionally sets on its main thread;"
      "# without it the log carries a 'could not set nice-level' line while realtime still works."
      "@${cfg.group} - rtprio ${toString cfg.rtprio}"
      "@${cfg.group} - nice ${toString cfg.nice}"
    ]
    ++ lib.optional (cfg.memlock != null) "@${cfg.group} - memlock ${toString cfg.memlock}"
  );
in
{
  options.nixaudio.rt = {
    enable = lib.mkEnableOption "realtime scheduling privileges for the audio group";

    group = lib.mkOption {
      type = lib.types.str;
      default = "audio";
      description = ''
        POSIX group granted the scheduling limits below, by NAME.

        Never a gid: `nixiam.posix` owns the fleet's uid/gid registry and converges device groups
        across machines. Declaring a number here would create a second, competing claim on one
        kernel namespace, and the disagreement would only surface on whichever machine lost.
      '';
    };

    rtprio = lib.mkOption {
      type = lib.types.ints.between 1 99;
      default = 95;
      description = ''
        Maximum realtime priority the group may request. This is the limit that actually governs
        audio thread scheduling.

        95 rather than 99 leaves headroom above the audio stack for anything that genuinely must
        preempt it (watchdogs, the kernel's own threads), which is the usual pro-audio guidance.
        PipeWire asks for far less than either — its data loops run at 20.
      '';
    };

    nice = lib.mkOption {
      type = lib.types.ints.between (-20) 0;
      default = -11;
      description = ''
        Most negative nice value the group may set. -11 is the value PipeWire's rt module asks for;
        anything less negative leaves the "could not set nice-level" complaint in the log.

        Cosmetic relative to `rtprio` — realtime scheduling works without it.
      '';
    };

    memlock = lib.mkOption {
      type = lib.types.nullOr (lib.types.either lib.types.ints.positive (lib.types.enum [ "unlimited" ]));
      default = null;
      description = ''
        Locked-memory limit in KB, or `"unlimited"`. Left unset by default: PipeWire does not
        require raised memlock, and raising it fleet-wide for a limit nothing asks for is a change
        without a reason. Set it if you run JACK clients that genuinely need it.
      '';
    };

    limitsConfig = lib.mkOption {
      type = lib.types.lines;
      internal = true;
      readOnly = true;
      default = limitsLines;
      description = "Generated limits.d content, consumed by whichever plane is in use.";
    };
  };

  config = lib.mkIf cfg.enable {
    security.pam.loginLimits = [
      { domain = "@${cfg.group}"; type = "-"; item = "rtprio"; value = toString cfg.rtprio; }
      { domain = "@${cfg.group}"; type = "-"; item = "nice"; value = toString cfg.nice; }
    ]
    ++ lib.optional (cfg.memlock != null) {
      domain = "@${cfg.group}";
      type = "-";
      item = "memlock";
      value = toString cfg.memlock;
    };

    assertions = [
      {
        # Only checkable when nixiam is actually composed. Where it is not, the group is assumed to
        # come from the distro (both Arch and NixOS ship an `audio` group by default).
        assertion = !nixiamComposed || (posixGroups ? ${cfg.group});
        message = ''
          nixaudio.rt.group is "${cfg.group}", but nixiam is composed on this host and does not
          declare that group in nixiam.posix.deviceGroups or nixiam.posix.groups.

          nixiam owns the fleet's uid/gid registry. Add the group there so its gid converges across
          machines, rather than letting each host's distro pick a number — an NFS export shared
          between two hosts that disagree grants access by NUMBER, not by name.
        '';
      }
    ];
  };
}
