# nixaudio.rt — the scheduling privileges PipeWire's realtime module needs.
#
# TWO DIFFERENT FAULTS WEAR THE SAME LOG LINE
#
# `mod.rt: could not set nice-level to -11: Permission denied` in the PipeWire log can mean either
# of two things, and they are not equally serious. Check which before believing anything else:
#
#   ps -Lo comm,cls,rtprio -C pipewire
#   ps -Lo comm,cls,rtprio -C jacktrip
#
# On a host that already has `@audio - rtprio 99` and a user in the group, the data loops come back
# `FF` — genuine realtime — and the only thing missing is RLIMIT_NICE, which governs the negative
# *nice* value PipeWire additionally asks for on its MAIN thread. A nicety, not the realtime path.
#
# On a host with no limits at all they come back `TS`, and so does every audio thread in the
# process tree. That is the serious one, and it is silent: JackTrip prints "Failed to set the
# scheduler policy and priority" once at startup and then runs anyway, badly. Measured on one such
# host against an otherwise identical one that had the grant: ~90x the xruns on the same hardware,
# same kernel, same binary, same quantum.
#
# So the fix is the same either way and the diagnosis is not. "Audio crackles" and "the main thread
# runs at nice 0" are different problems, and conflating them sends the next person down the wrong
# path — which is exactly what an earlier version of this comment did, by reporting one host's
# healthy `SCHED_RR 20` as though it were what every host looks like.
#
# ── WHY THE GROUP IS A NAME AND NEVER A NUMBER ──────────────────────────────────────────────────
#
# A limits line keyed on a group NAME resolves through whatever uid/gid registry the deployment
# keeps, so the number can converge across machines however that deployment arranges it. A module
# that invented its own gid would be declaring a second, competing number for one kernel namespace,
# and the failure only shows up on the machine where the two disagree.
#
# So this module names the group and never numbers it. Where a registry is composed, an assertion
# checks the group is actually declared there rather than assuming it exists.
{ lib, config, ... }:
let
  cfg = config.nixaudio.rt;

  posixGroups = (config.nixiam.posix.deviceGroups or { }) // (config.nixiam.posix.groups or { });
  nixiamComposed = config ? nixiam;

  limitsLines = lib.concatStringsSep "\n" (
    [
      "# Generated by nixaudio.rt -- do not edit."
      "#"
      "# rtprio governs the realtime scheduling the audio threads actually use."
      "# nice governs only the negative nice value PipeWire additionally sets on its main thread;"
      "# without it the log carries a 'could not set nice-level' line while realtime still works."
      "@${cfg.group} - rtprio ${toString cfg.rtprio}"
      "@${cfg.group} - nice ${toString cfg.nice}"
    ]
    ++ lib.optional (cfg.memlock != null) "@${cfg.group} - memlock ${toString cfg.memlock}"
  );
in
{
  options.nixaudio.rt = {
    enable = lib.mkEnableOption "realtime scheduling privileges for the audio group";

    group = lib.mkOption {
      type = lib.types.str;
      default = "audio";
      description = ''
        POSIX group granted the scheduling limits below, by NAME.

        Never a gid. Wherever a deployment keeps its uid/gid registry, that is what converges the
        number across machines; declaring one here would create a second, competing claim on a
        single kernel namespace, and the disagreement would surface only on whichever machine lost.
        `nixiam.posix` is read when it happens to be composed, and assumed absent otherwise.
      '';
    };

    rtprio = lib.mkOption {
      type = lib.types.ints.between 1 99;
      default = 95;
      description = ''
        Maximum realtime priority the group may request. This is the limit that actually governs
        audio thread scheduling.

        95 rather than 99 leaves headroom above the audio stack for anything that genuinely must
        preempt it (watchdogs, the kernel's own threads), which is the usual pro-audio guidance.
        PipeWire asks for far less than either: its data loops typically run in the twenties to the
        high eighties depending on how the distribution configures them.
      '';
    };

    nice = lib.mkOption {
      type = lib.types.ints.between (-20) 0;
      default = -11;
      description = ''
        Most negative nice value the group may set. -11 is the value PipeWire's rt module asks for;
        anything less negative leaves the "could not set nice-level" complaint in the log.

        Cosmetic relative to `rtprio` — realtime scheduling works without it.
      '';
    };

    memlock = lib.mkOption {
      type = lib.types.nullOr (lib.types.either lib.types.ints.positive (lib.types.enum [ "unlimited" ]));
      default = null;
      description = ''
        Locked-memory limit in KB, or `"unlimited"`. Left unset by default: PipeWire does not
        require raised memlock, and raising it on every host for a limit nothing asks for is a change
        without a reason. Set it if you run JACK clients that genuinely need it.
      '';
    };

    limitsConfig = lib.mkOption {
      type = lib.types.lines;
      internal = true;
      readOnly = true;
      default = limitsLines;
      description = "Generated limits.d content, consumed by whichever plane is in use.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        # Only checkable when nixiam is actually composed. Where it is not, the group is assumed to
        # come from the distro (both Arch and NixOS ship an `audio` group by default).
        assertion = !nixiamComposed || (posixGroups ? ${cfg.group});
        message = ''
          nixaudio.rt.group is "${cfg.group}", but nixiam is composed on this host and does not
          declare that group in nixiam.posix.deviceGroups or nixiam.posix.groups.

          Add the group to that registry so its gid converges across machines, rather than letting
          each host's distribution pick a number independently. Anything that grants access by
          NUMBER rather than by name — a shared network filesystem, most obviously — breaks on the
          machine where the two disagree, and nowhere else.
        '';
      }
    ];
  };
}
